/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IMS;

import javax.swing.JOptionPane;

/**
 *
 * @author Raidi
 * 
 * NOTE: THIS JAVA CLASS IS OLD, I HAVE A NEW AND REWORKED VER.
 * DELETE THIS IF AND ONLY IF THE NEW ONE IS WORKING.
 */
public class CustomerRegisterOldShit extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegister
     */
    public CustomerRegisterOldShit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        customerUR = new javax.swing.JTextField();
        customerPR = new javax.swing.JTextField();
        customerER = new javax.swing.JTextField();
        confirmlogin = new javax.swing.JButton();
        registerconfirm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Register");
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 80, 83, 25);

        customerUR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(customerUR);
        customerUR.setBounds(250, 110, 230, 25);

        customerPR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(customerPR);
        customerPR.setBounds(250, 170, 330, 25);

        customerER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(customerER);
        customerER.setBounds(250, 240, 330, 30);

        confirmlogin.setText("Login");
        confirmlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmloginActionPerformed(evt);
            }
        });
        getContentPane().add(confirmlogin);
        confirmlogin.setBounds(350, 290, 80, 30);

        registerconfirm.setText("Register");
        registerconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerconfirmActionPerformed(evt);
            }
        });
        getContentPane().add(registerconfirm);
        registerconfirm.setBounds(250, 290, 90, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 210, 42, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 80, 83, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Username:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 80, 83, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmloginActionPerformed
        // Sends the Customer back to the Login page
        dispose();
        CustomerLogin sendback = new CustomerLogin();
        sendback.setVisible(true);
    }//GEN-LAST:event_confirmloginActionPerformed

    private void registerconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerconfirmActionPerformed
        // Confirms the Customer's Registration
        
        // Customer's Detials
        String usernamereg = customerUR.getText();
        String passwordreg = customerPR.getText();
        String emailreg = customerER.getText();
        
        
        // The set conditions
        if(usernamereg.isEmpty() || passwordreg.isEmpty() || emailreg.isEmpty()){
            // Ensure the details are filled
            JOptionPane.showMessageDialog(this,"Check if you have filled all","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,"Your Details has been stored!");
        }
    }//GEN-LAST:event_registerconfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterOldShit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterOldShit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterOldShit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterOldShit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegisterOldShit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmlogin;
    private javax.swing.JTextField customerER;
    private javax.swing.JTextField customerPR;
    private javax.swing.JTextField customerUR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton registerconfirm;
    // End of variables declaration//GEN-END:variables
}
