/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IMS;

import javax.swing.JOptionPane;
/**
 *
 * @author Raidi
 */
public class CustomerLogin extends javax.swing.JFrame {

    /**
     * Creates new form CusomerLoginfromRegiser
     */
    public CustomerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerusernamelogin = new javax.swing.JTextField();
        costumerconfirmlogin = new javax.swing.JButton();
        customeregistering = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        customerspasswordlogin = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Login");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        customerusernamelogin.setForeground(new java.awt.Color(102, 102, 102));
        customerusernamelogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        customerusernamelogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerusernameloginActionPerformed(evt);
            }
        });
        getContentPane().add(customerusernamelogin);
        customerusernamelogin.setBounds(430, 150, 320, 40);

        costumerconfirmlogin.setBackground(new java.awt.Color(102, 102, 102));
        costumerconfirmlogin.setForeground(new java.awt.Color(255, 255, 255));
        costumerconfirmlogin.setText("Login");
        costumerconfirmlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costumerconfirmloginActionPerformed(evt);
            }
        });
        getContentPane().add(costumerconfirmlogin);
        costumerconfirmlogin.setBounds(430, 320, 91, 35);

        customeregistering.setForeground(new java.awt.Color(51, 51, 51));
        customeregistering.setText("Register");
        customeregistering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeregisteringActionPerformed(evt);
            }
        });
        getContentPane().add(customeregistering);
        customeregistering.setBounds(580, 400, 80, 30);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMS/FantasticFourLogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO LIQUOR STORE ");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Where the finest spirits meet your taste.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 500);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 20, 130, 80);

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Username");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 20));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(18, 102, 141, 20);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 120, 70, 18);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 200, 80, 18);

        customerspasswordlogin.setForeground(new java.awt.Color(102, 102, 102));
        customerspasswordlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerspasswordloginActionPerformed(evt);
            }
        });
        getContentPane().add(customerspasswordlogin);
        customerspasswordlogin.setBounds(430, 230, 320, 40);
        customerspasswordlogin.getAccessibleContext().setAccessibleName("");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("I don't have an account?");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 400, 150, 30);

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 400, 72, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costumerconfirmloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costumerconfirmloginActionPerformed
        // Entered / Stored Customer Details
        // CustomerRegister customerreg = new CustomerRegister();
        
        // Costumer confirms to login
        String usernamelog = customerusernamelogin.getText();
        String passwordlog = customerspasswordlogin.getText();
        
        if(usernamelog.isEmpty() || passwordlog.isEmpty()){
            // Ensure user filled the text
            JOptionPane.showMessageDialog(this,"Check if you have filled all","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(usernamelog.equals("drunkard") && passwordlog.equals("456")){ // That is a place holder for now
            // Entered details are not the same
            dispose();
            CustomerProfile seeprofile = new CustomerProfile();
            seeprofile.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Incorrect Username and Password!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_costumerconfirmloginActionPerformed

    private void customeregisteringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeregisteringActionPerformed
        // Goes to the Register Form for Customers
        dispose();
        CustomerRegister customerreg = new CustomerRegister();
        customerreg.setVisible(true);
    }//GEN-LAST:event_customeregisteringActionPerformed

    private void customerusernameloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerusernameloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerusernameloginActionPerformed

    private void customerspasswordloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerspasswordloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerspasswordloginActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        userType userTypeFrame = new userType();
        userTypeFrame.setVisible(true);
        userTypeFrame.pack();
        userTypeFrame.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton costumerconfirmlogin;
    private javax.swing.JButton customeregistering;
    private javax.swing.JPasswordField customerspasswordlogin;
    private javax.swing.JTextField customerusernamelogin;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
